### PR TITLE
env: Added draft feature

### PR DESCRIPTION
**Pull request by heyman333**
hello @JaeYeopHan 
Could u please check my update?

I'm already using this feature on my blog.
But I'm not used to writing `graphQL`, I'd appreciate it if you review it.

### CODE REVIEW

**Comment by JaeYeopHan** [comment]
@heyman333 hi :)

awesome feature! thank you so much.
i think we have to consider some more.

1. Currently creating a post using the CLI tool, which seems to need to be added. ([here](https://github.com/JaeYeopHan/gatsby-starter-bee/blob/master/cli/create-new-post.js#L137))
2. If the default value of the draft flag is `false`, it may be possible for newbie to think that their writing is not deployed. It would be nice to have a safeguard for this.
3. Combining stories 1 and 2, how about making the draft's default value `true` in the cli tool?
4. And... I think it would be nice to add something here too. ([docs](https://github.com/JaeYeopHan/gatsby-starter-bee/blob/master/content/blog/development/hello.md#1-support-three-frontmatter))

thanks :)

**Comment by heyman333** [comment]
@JaeYeopHan 
Really Thank you for your kind review!
I'll fix what you said again ASAP
I learned a lot from you :D

**Comment by JaeYeopHan** [comment]
@heyman333  oh thanks! :)
maybe you have to check this:

스크린샷 2019-12-08 오후 12 19 16

> When I write a new post, I create a new branch and working on created branch. (and merge to master branch for publishing) So I didn't need the draft feature 😅

**Comment by heyman333** [comment]
@JaeYeopHan 
Okay, I'll have to check that part too!

If you think it's unnecessary, you may close it 😀
But, As you know some of the other starter's been providing a `draft feature` on post

**Comment by heyman333** [comment]
@JaeYeopHan 
It seems that all the modifications that you mentioned have been modified. 
`CI` throw the error with the the process of building.

can u check it?

**Comment by JaeYeopHan** [comment]
@heyman333 Please dismiss travis error. i will migrate to github action. (plan...)

**Pull request merged**
